development:
  dialect: postgres
  database: riskman
  user: riskman
  password: riskman
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://riskman:riskman@testdb:5432/riskman_test?sslmode=disable"}}

staging:
  url: {{envOr "DATABASE_URL" "postgres://riskman:riskman@127.0.0.1:5432/riskman_staging?sslmode=disable"}}

prod:
  url: {{envOr "DATABASE_URL" "postgres://riskman:riskman@127.0.0.1:5432/riskman_production?sslmode=disable"}}
